### ISSUE TITLE
RoadMap: ecommerce

### ISSUE THREAD

**Issue by oladhari** [oladhari/e-commerce#1]
## frontend

- [x] add page Product list with categories
- [x] #10
- [x] add the cart page
- [ ] add the payment page

## backend

- [x] add the models related to products, and cart
- [x] create a related API
- [x] connect the API with the fronted

## deployment

- [ ] dockerize the whole application
- [ ] use Kubernetes for containers
- [ ] connect media and static files to cloud storage (Google or Amazon)
- [ ] deploy to google cloud or AWS (check the free options)

**Comment by Farid212** [comment]
I will work a little bit this night...

**Comment by oladhari** [comment]
> I will work a little bit this night...

thank you, if you can, just enjoy your holidays
if you are going to work, can you override the home page? make a banner and list the categories?
